/*
 * codegen.c -- small canned snippets for Python, JavaScript, HTML and CSS.
 *
 * Nothing is generated by a model here; every snippet is written out by hand
 * and picked by keyword overlap, in the same spirit as the chat script itself.
 * It only fires when the user clearly asks for code, so ordinary chat is
 * untouched.
 */
#include <stdio.h>
#include <string.h>
#include <ctype.h>

#include "codegen.h"

#define MAX_CODE_LINES 32

typedef struct {
    const char *keys;   /* space separated words/phrases that select this snippet */
    const char *title;
    const char *code[MAX_CODE_LINES];
} Snippet;

typedef struct {
    const char *name;     /* canonical name, printed in the code fence */
    const char *label;    /* pretty name, printed in the sentence */
    const char *aliases;  /* words in the input that select this language */
    const char *menu;     /* what to list when we do not know the topic */
    const Snippet *snips;
} Lang;

/* ------------------------------------------------------------------ python */

static const Snippet PY[] = {
{ "hello world hello-world helloworld first program start", "print hello world", {
    "print(\"Hello, world!\")", NULL } },

{ "input name ask user read input", "ask for a name and greet the user", {
    "name = input(\"What is your name? \")",
    "print(f\"Hello, {name}! Nice to meet you.\")", NULL } },

{ "loop for count counting numbers repeat", "count from 1 to 5 with a loop", {
    "for i in range(1, 6):",
    "    print(i)", NULL } },

{ "while countdown until", "count down with a while loop", {
    "n = 5",
    "while n > 0:",
    "    print(n)",
    "    n -= 1",
    "print(\"Liftoff!\")", NULL } },

{ "function def return argument arguments parameter", "write a function", {
    "def greet(name, greeting=\"Hello\"):",
    "    return f\"{greeting}, {name}!\"",
    "",
    "print(greet(\"Ada\"))",
    "print(greet(\"Ada\", greeting=\"Good morning\"))", NULL } },

{ "reverse string backwards flip", "reverse a string", {
    "text = \"chatbot\"",
    "print(text[::-1])          # tobtahc",
    "",
    "# the same thing spelled out",
    "def reverse(s):",
    "    return \"\".join(reversed(s))", NULL } },

{ "list sort sorted order array", "sort a list", {
    "names = [\"Cleo\", \"ada\", \"Grace\", \"bob\"]",
    "",
    "print(sorted(names))                      # capitals first",
    "print(sorted(names, key=str.lower))       # ignore case",
    "print(sorted(names, key=len, reverse=True))  # longest first", NULL } },

{ "dict dictionary map key value lookup json", "use a dictionary", {
    "ages = {\"ada\": 36, \"grace\": 45}",
    "",
    "ages[\"alan\"] = 41            # add",
    "print(ages[\"ada\"])           # 36",
    "print(ages.get(\"nobody\", 0))  # 0 instead of an error",
    "",
    "for name, age in ages.items():",
    "    print(name, \"is\", age)", NULL } },

{ "read file open lines text load", "read a text file line by line", {
    "with open(\"notes.txt\", \"r\", encoding=\"utf-8\") as f:",
    "    for line in f:",
    "        print(line.rstrip())", NULL } },

{ "write file save output", "write a text file", {
    "lines = [\"first\", \"second\", \"third\"]",
    "",
    "with open(\"notes.txt\", \"w\", encoding=\"utf-8\") as f:",
    "    for line in lines:",
    "        f.write(line + \"\\n\")", NULL } },

{ "random number dice guess", "pick a random number", {
    "import random",
    "",
    "print(random.randint(1, 6))            # a dice roll",
    "print(random.choice([\"yes\", \"no\"]))    # pick from a list", NULL } },

{ "fizzbuzz fizz buzz", "solve fizzbuzz", {
    "for i in range(1, 21):",
    "    if i % 15 == 0:",
    "        print(\"FizzBuzz\")",
    "    elif i % 3 == 0:",
    "        print(\"Fizz\")",
    "    elif i % 5 == 0:",
    "        print(\"Buzz\")",
    "    else:",
    "        print(i)", NULL } },

{ "class object oop method init", "write a class", {
    "class Dog:",
    "    def __init__(self, name):",
    "        self.name = name",
    "",
    "    def speak(self):",
    "        return f\"{self.name} says woof\"",
    "",
    "rex = Dog(\"Rex\")",
    "print(rex.speak())", NULL } },

{ "timer clock time sleep wait", "wait between two messages", {
    "import time",
    "",
    "print(\"working...\")",
    "time.sleep(2)          # two seconds",
    "print(\"done\")", NULL } },

{ "calculator add math sum average", "add up numbers and average them", {
    "numbers = [4, 8, 15, 16, 23, 42]",
    "",
    "print(sum(numbers))                    # 108",
    "print(sum(numbers) / len(numbers))     # 18.0",
    "print(max(numbers), min(numbers))      # 42 4", NULL } },

{ "script main argv command line arguments", "make a runnable script", {
    "import sys",
    "",
    "def main(args):",
    "    if not args:",
    "        print(\"give me a word to shout\")",
    "        return 1",
    "    print(args[0].upper() + \"!\")",
    "    return 0",
    "",
    "if __name__ == \"__main__\":",
    "    sys.exit(main(sys.argv[1:]))", NULL } },

{ NULL, NULL, { NULL } }
};

/* -------------------------------------------------------------- javascript */

static const Snippet JS[] = {
{ "hello world hello-world helloworld log console first", "print hello world", {
    "console.log(\"Hello, world!\");", NULL } },

{ "function arrow return argument arguments parameter", "write a function", {
    "function greet(name, greeting = \"Hello\") {",
    "  return `${greeting}, ${name}!`;",
    "}",
    "",
    "// the same function as an arrow",
    "const greet2 = (name) => `Hello, ${name}!`;",
    "",
    "console.log(greet(\"Ada\"));", NULL } },

{ "loop for count counting repeat numbers", "count from 1 to 5 with a loop", {
    "for (let i = 1; i <= 5; i++) {",
    "  console.log(i);",
    "}",
    "",
    "// or over a list",
    "for (const fruit of [\"apple\", \"pear\"]) {",
    "  console.log(fruit);",
    "}", NULL } },

{ "button click handler onclick event listener press", "run code when a button is clicked", {
    "// pair this with: <button id=\"go\">Click me</button>",
    "const button = document.getElementById(\"go\");",
    "let count = 0;",
    "",
    "button.addEventListener(\"click\", () => {",
    "  count += 1;",
    "  button.textContent = `Clicked ${count} times`;",
    "});", NULL } },

{ "array map filter reduce list transform", "work through an array", {
    "const numbers = [4, 8, 15, 16, 23, 42];",
    "",
    "const doubled = numbers.map((n) => n * 2);",
    "const big = numbers.filter((n) => n > 15);",
    "const total = numbers.reduce((sum, n) => sum + n, 0);",
    "",
    "console.log(doubled, big, total);", NULL } },

{ "sort order sorted", "sort an array", {
    "const names = [\"Cleo\", \"ada\", \"Grace\"];",
    "const numbers = [10, 9, 100, 1];",
    "",
    "console.log([...names].sort((a, b) => a.localeCompare(b)));",
    "console.log([...numbers].sort((a, b) => a - b));  // numbers need the compare", NULL } },

{ "reverse string backwards flip", "reverse a string", {
    "const text = \"chatbot\";",
    "const backwards = [...text].reverse().join(\"\");",
    "",
    "console.log(backwards);  // tobtahc", NULL } },

{ "random number dice guess", "pick a random number", {
    "// a whole number from 1 to 6",
    "const roll = Math.floor(Math.random() * 6) + 1;",
    "console.log(roll);",
    "",
    "const pick = [\"yes\", \"no\"][Math.floor(Math.random() * 2)];",
    "console.log(pick);", NULL } },

{ "timer interval setinterval settimeout clock wait delay", "run something on a timer", {
    "// once, after two seconds",
    "setTimeout(() => console.log(\"two seconds later\"), 2000);",
    "",
    "// every second, then stop after five ticks",
    "let ticks = 0;",
    "const id = setInterval(() => {",
    "  console.log(++ticks);",
    "  if (ticks === 5) clearInterval(id);",
    "}, 1000);", NULL } },

{ "fetch request api url http json download", "fetch some JSON from a URL", {
    "async function load(url) {",
    "  const response = await fetch(url);",
    "  if (!response.ok) throw new Error(`HTTP ${response.status}`);",
    "  return response.json();",
    "}",
    "",
    "load(\"https://example.com/data.json\")",
    "  .then((data) => console.log(data))",
    "  .catch((err) => console.error(err.message));", NULL } },

{ "class object oop method constructor", "write a class", {
    "class Dog {",
    "  constructor(name) {",
    "    this.name = name;",
    "  }",
    "",
    "  speak() {",
    "    return `${this.name} says woof`;",
    "  }",
    "}",
    "",
    "console.log(new Dog(\"Rex\").speak());", NULL } },

{ "input form value read field text box", "read what someone typed into a field", {
    "// pair this with: <input id=\"who\"> <button id=\"go\">Greet</button>",
    "document.getElementById(\"go\").addEventListener(\"click\", () => {",
    "  const value = document.getElementById(\"who\").value.trim();",
    "  alert(value ? `Hello, ${value}!` : \"Type a name first.\");",
    "});", NULL } },

{ "object dict map key value json", "use an object as a lookup table", {
    "const ages = { ada: 36, grace: 45 };",
    "",
    "ages.alan = 41;",
    "console.log(ages.ada);          // 36",
    "console.log(ages.nobody ?? 0);  // 0 instead of undefined",
    "",
    "for (const [name, age] of Object.entries(ages)) {",
    "  console.log(name, \"is\", age);",
    "}", NULL } },

{ "change text content element dom update html", "change text on the page", {
    "const box = document.querySelector(\"#message\");",
    "box.textContent = \"Updated from JavaScript.\";",
    "box.classList.add(\"highlight\");", NULL } },

{ NULL, NULL, { NULL } }
};

/* -------------------------------------------------------------------- html */

static const Snippet HTML[] = {
{ "page boilerplate template starter skeleton document blank basic", "start a page", {
    "<!DOCTYPE html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\">",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    "  <title>My page</title>",
    "  <link rel=\"stylesheet\" href=\"style.css\">",
    "</head>",
    "<body>",
    "  <h1>My page</h1>",
    "  <p>Hello, world!</p>",
    "  <script src=\"main.js\"></script>",
    "</body>",
    "</html>", NULL } },

{ "button click press", "add a button", {
    "<button id=\"go\" type=\"button\" class=\"btn\">Click me</button>",
    "",
    "<!-- with a bit of JavaScript attached -->",
    "<script>",
    "  document.getElementById(\"go\").onclick = () => alert(\"Clicked!\");",
    "</script>", NULL } },

{ "form input submit field text email login", "build a small form", {
    "<form action=\"/signup\" method=\"post\">",
    "  <label for=\"name\">Name</label>",
    "  <input id=\"name\" name=\"name\" type=\"text\" required>",
    "",
    "  <label for=\"email\">Email</label>",
    "  <input id=\"email\" name=\"email\" type=\"email\" required>",
    "",
    "  <button type=\"submit\">Sign up</button>",
    "</form>", NULL } },

{ "table rows columns grid data", "make a table", {
    "<table>",
    "  <thead>",
    "    <tr><th>Name</th><th>Born</th></tr>",
    "  </thead>",
    "  <tbody>",
    "    <tr><td>Ada Lovelace</td><td>1815</td></tr>",
    "    <tr><td>Grace Hopper</td><td>1906</td></tr>",
    "  </tbody>",
    "</table>", NULL } },

{ "list bullet items ordered unordered", "make a list", {
    "<ul>",
    "  <li>First thing</li>",
    "  <li>Second thing</li>",
    "</ul>",
    "",
    "<ol>",
    "  <li>Step one</li>",
    "  <li>Step two</li>",
    "</ol>", NULL } },

{ "image picture photo img", "show an image", {
    "<img src=\"cat.jpg\" alt=\"A cat asleep on a keyboard\" width=\"400\">",
    "",
    "<!-- alt text is not optional; screen readers read it aloud -->", NULL } },

{ "link anchor href url navigate", "add a link", {
    "<a href=\"https://example.com\">Visit example.com</a>",
    "",
    "<!-- opening in a new tab safely -->",
    "<a href=\"https://example.com\" target=\"_blank\" rel=\"noopener\">New tab</a>", NULL } },

{ "nav menu header navigation bar", "add a navigation bar", {
    "<nav class=\"nav\">",
    "  <a href=\"/\">Home</a>",
    "  <a href=\"/about\">About</a>",
    "  <a href=\"/contact\">Contact</a>",
    "</nav>", NULL } },

{ "card box panel", "make a card", {
    "<div class=\"card\">",
    "  <h2>Card title</h2>",
    "  <p>A short line of text inside the card.</p>",
    "  <button type=\"button\">Do the thing</button>",
    "</div>", NULL } },

{ NULL, NULL, { NULL } }
};

/* --------------------------------------------------------------------- css */

static const Snippet CSS[] = {
{ "center centre middle div vertical horizontal", "centre a box on the screen", {
    "body {",
    "  min-height: 100vh;",
    "  margin: 0;",
    "  display: flex;",
    "  align-items: center;      /* vertical */",
    "  justify-content: center;  /* horizontal */",
    "}", NULL } },

{ "button btn style press", "style a button", {
    ".btn {",
    "  padding: 0.6rem 1.2rem;",
    "  border: none;",
    "  border-radius: 8px;",
    "  background: #2f6fed;",
    "  color: #fff;",
    "  font: inherit;",
    "  cursor: pointer;",
    "  transition: background 0.15s ease;",
    "}",
    "",
    ".btn:hover  { background: #2559c4; }",
    ".btn:active { transform: translateY(1px); }",
    ".btn:focus-visible { outline: 3px solid #9bc0ff; outline-offset: 2px; }", NULL } },

{ "flex flexbox row column layout space", "lay things out in a row", {
    ".row {",
    "  display: flex;",
    "  gap: 1rem;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  flex-wrap: wrap;    /* stack instead of overflowing on small screens */",
    "}", NULL } },

{ "grid columns gallery layout", "lay out a responsive grid", {
    ".grid {",
    "  display: grid;",
    "  gap: 1rem;",
    "  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));",
    "}", NULL } },

{ "hover effect transition animation", "add a hover effect", {
    ".card {",
    "  transition: transform 0.2s ease, box-shadow 0.2s ease;",
    "}",
    "",
    ".card:hover {",
    "  transform: translateY(-4px);",
    "  box-shadow: 0 10px 24px rgba(0, 0, 0, 0.18);",
    "}", NULL } },

{ "card box shadow rounded corners panel", "style a card", {
    ".card {",
    "  max-width: 22rem;",
    "  padding: 1.25rem;",
    "  border-radius: 12px;",
    "  background: #fff;",
    "  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);",
    "}", NULL } },

{ "dark mode theme colours colors night", "support light and dark mode", {
    ":root {",
    "  --bg: #ffffff;",
    "  --text: #16181d;",
    "  --accent: #2f6fed;",
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    "  :root {",
    "    --bg: #14161a;",
    "    --text: #e8e9ec;",
    "    --accent: #7aa2ff;",
    "  }",
    "}",
    "",
    "body { background: var(--bg); color: var(--text); }",
    "a    { color: var(--accent); }", NULL } },

{ "font text typography family size readable", "set readable type", {
    "body {",
    "  font-family: system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;",
    "  font-size: 1.05rem;",
    "  line-height: 1.6;",
    "  max-width: 42rem;   /* stops long lines being hard to read */",
    "  margin: 2rem auto;",
    "  padding: 0 1rem;",
    "}", NULL } },

{ "responsive media query mobile phone screen", "change the layout on small screens", {
    ".sidebar { width: 18rem; float: left; }",
    "",
    "@media (max-width: 40rem) {",
    "  .sidebar {",
    "    width: auto;",
    "    float: none;",
    "  }",
    "}", NULL } },

{ "nav menu bar navigation header", "style a navigation bar", {
    ".nav {",
    "  display: flex;",
    "  gap: 1.25rem;",
    "  padding: 1rem;",
    "  background: #16181d;",
    "}",
    "",
    ".nav a {",
    "  color: #e8e9ec;",
    "  text-decoration: none;",
    "}",
    "",
    ".nav a:hover { text-decoration: underline; }", NULL } },

{ "background gradient colour color", "add a gradient background", {
    "body {",
    "  min-height: 100vh;",
    "  margin: 0;",
    "  background: linear-gradient(160deg, #2f6fed, #8b5cf6);",
    "  color: #fff;",
    "}", NULL } },

{ NULL, NULL, { NULL } }
};

/* ----------------------------------------------------------------- tables */

static const Lang LANGS[] = {
{ "python", "Python", "python py python3 py3",
  "hello world, ask for input, a loop, a function, reverse a string, sort a list, "
  "a dictionary, read or write a file, a random number, fizzbuzz, a class, a script",
  PY },
{ "javascript", "JavaScript", "javascript js node nodejs ecmascript",
  "hello world, a function, a loop, a button click handler, map or filter an array, "
  "sort an array, reverse a string, a random number, a timer, fetch a URL, a class",
  JS },
{ "html", "HTML", "html html5 webpage",
  "a starter page, a button, a form, a table, a list, an image, a link, a nav bar, a card",
  HTML },
{ "css", "CSS", "css stylesheet styles",
  "centre a box, style a button, a flexbox row, a responsive grid, a hover effect, "
  "a card, dark mode, readable fonts, a media query, a nav bar, a gradient",
  CSS },
{ NULL, NULL, NULL, NULL, NULL }
};

/* Words that tell us the user wants code rather than conversation. */
static const char *REQUEST_WORDS[] = {
    "make", "write", "give", "show", "create", "generate", "build", "code",
    "snippet", "example", "how do i", "how to", "teach me", "need", "want",
    "help me with", NULL
};

/* ---------------------------------------------------------------- helpers */

/*
 * Word aware search: does `needle` (one word, or a phrase) appear in `hay`
 * on word boundaries? `hay` is already lower case with single spaces.
 */
static int has_phrase(const char *hay, const char *needle)
{
    size_t nlen = strlen(needle);
    const char *p = hay;

    while ((p = strstr(p, needle)) != NULL) {
        int left_ok  = (p == hay) || (p[-1] == ' ');
        char after   = p[nlen];
        int right_ok = (after == '\0' || after == ' ');
        if (left_ok && right_ok)
            return 1;
        p += 1;
    }
    return 0;
}

/* Count how many of a space separated key list appear in the input. */
static int score_keys(const char *input, const char *keys)
{
    char word[64];
    size_t w = 0;
    int score = 0;

    for (const char *p = keys;; p++) {
        if (*p != ' ' && *p != '\0') {
            if (w + 1 < sizeof word)
                word[w++] = *p;
            continue;
        }
        word[w] = '\0';
        if (w > 0 && has_phrase(input, word))
            score++;
        w = 0;
        if (*p == '\0')
            break;
    }
    return score;
}

static void app(char *out, size_t outsz, const char *s)
{
    size_t n = strlen(out);
    if (n + 1 >= outsz)
        return;
    snprintf(out + n, outsz - n, "%s", s);
}

static const Lang *find_lang(const char *input)
{
    for (const Lang *l = LANGS; l->name; l++) {
        char alias[32];
        size_t w = 0;
        for (const char *p = l->aliases;; p++) {
            if (*p != ' ' && *p != '\0') {
                if (w + 1 < sizeof alias)
                    alias[w++] = *p;
                continue;
            }
            alias[w] = '\0';
            if (w > 0 && has_phrase(input, alias))
                return l;
            w = 0;
            if (*p == '\0')
                break;
        }
    }
    return NULL;
}

static int wants_code(const char *input)
{
    for (const char **r = REQUEST_WORDS; *r; r++)
        if (has_phrase(input, *r))
            return 1;
    return 0;
}

static void emit(const Lang *lang, const Snippet *s, int lead,
                 char *out, size_t outsz)
{
    char line[256];

    if (lead) {
        snprintf(line, sizeof line, "Certainly. Here is a little %s to %s:\n\n",
                 lang->label, s->title);
        app(out, outsz, line);
    }

    snprintf(line, sizeof line, "--- %s ---\n", lang->name);
    app(out, outsz, line);

    for (const char *const *c = s->code; *c; c++) {
        app(out, outsz, *c);
        app(out, outsz, "\n");
    }

    app(out, outsz, "--- end ---");
}

/* ------------------------------------------------------------------- api */

void codegen_usage(char *out, size_t outsz)
{
    out[0] = '\0';
    app(out, outsz,
        "I can write small pieces of Python, JavaScript, HTML and CSS.\n"
        "Just ask in plain words, for example:\n\n"
        "  make me a button in css\n"
        "  write hello world in py\n"
        "  show me a loop in javascript\n"
        "  give me a form in html\n\n"
        "Or be explicit:  /code css dark mode\n"
        "Everything else I hear, I will simply talk with you about.");
}

int codegen_try(const char *input, char *out, size_t outsz)
{
    const Lang *lang;
    const Snippet *best = NULL;
    int best_score = 0;
    int explicit_cmd = 0;

    if (input == NULL || input[0] == '\0')
        return 0;

    /* "/code ..." always means business. */
    if (strncmp(input, "code ", 5) == 0 || strcmp(input, "code") == 0)
        explicit_cmd = 1;

    lang = find_lang(input);
    if (lang == NULL) {
        if (explicit_cmd) {
            out[0] = '\0';
            codegen_usage(out, outsz);
            return 1;
        }
        return 0;
    }

    if (!explicit_cmd && !wants_code(input))
        return 0;

    for (const Snippet *s = lang->snips; s->keys; s++) {
        int score = score_keys(input, s->keys);
        if (score > best_score) {
            best_score = score;
            best = s;
        }
    }

    out[0] = '\0';

    if (best == NULL) {
        char line[512];
        snprintf(line, sizeof line,
                 "I am not sure which piece of %s you want, so here is a "
                 "starting point:\n\n", lang->label);
        app(out, outsz, line);
        emit(lang, &lang->snips[0], 0, out, outsz);

        snprintf(line, sizeof line,
                 "\n\nIn %s I can also show you: %s.\nAsk me for any of those.",
                 lang->label, lang->menu);
        app(out, outsz, line);
        return 1;
    }

    emit(lang, best, 1, out, outsz);
    app(out, outsz,
        "\n\nNow, where were we? Tell me more about what you were saying.");
    return 1;
}
