#!/usr/bin/env python3
"""
prepare.py -- turn instruction data into something the model can learn from.

Two sources, both turned into the same <user>/<bot> turn format:

  - the Stanford Alpaca dataset (52,000 instruction -> response pairs, written
    to train a helpful assistant rather than transcribed from film scripts)
  - WikiText-2 (real Wikipedia article text, used as-is by NLP researchers),
    turned into "tell me about <title>" -> <opening paragraph> pairs

Reddit was asked for too, but nothing usable is reachable from here: the
Reddit API, Pushshift, and Wikipedia's own API/dumps servers are all
unreachable from this sandbox (only plain files on GitHub are); rather than
fake it, this only uses what is genuinely available. See the note in
load_wiki() if you want to point it at something else.

    python3 train/prepare.py            # downloads both sources if missing

Everything lands in data/:

    alpaca_data.json   raw Alpaca dataset (downloaded once)
    wikitext2.txt      raw WikiText-2 dataset (downloaded once)
    vocab.txt           one word per line, most common first
    corpus.bin           the training data: little endian uint16 token ids
    corpus.txt           the same thing readable, for when you are curious
"""

from __future__ import annotations

import json
import re
import struct
import sys
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

ALPACA_URL = ("https://raw.githubusercontent.com/tatsu-lab/"
              "stanford_alpaca/main/alpaca_data.json")
ALPACA_FILE = "alpaca_data.json"

WIKI_URL = ("https://raw.githubusercontent.com/pytorch/examples/main/"
            "word_language_model/data/wikitext-2/train.txt")
WIKI_FILE = "wikitext2.txt"

VOCAB_SIZE = 8000          # words kept; everything else becomes <unk>
MAX_PROMPT_WORDS = 50      # instruction (+ input), combined
MAX_OUTPUT_WORDS = 80      # drop the long-tail essays; keeps windows short
MIN_OUTPUT_WORDS = 1
MAX_UNK_RATE = 0.15        # skip an example that is mostly words we do not know

# Anything outside these characters (case-insensitive) is a sign the answer is
# code, a table, or markdown -- not the kind of prose a word-level model can
# represent -- so a high ratio of them means "skip this one".
ALLOWED_CHARS = re.compile(r"[a-z0-9.,!?;:' \n\-]")

# Alpaca's answers were generated by an OpenAI model, and it shows: some of them
# claim to *be* one. Vespra is trained from scratch, on your machine, by nobody's
# API -- so training examples that assert otherwise are dropped rather than
# taught as if they were true.
IDENTITY_LEAKS = [
    "language model", "openai", "chatgpt", "gpt-3", "gpt-4", "gpt3", "gpt4",
    "gpt model", "gpt language", "as a gpt", "nooutput", "cannot be fulfilled",
    "as an ai", "i am an ai", "i'm an ai", "an ai assistant",
    "artificial intelligence created by", "trained by openai",
    "i do not have the ability", "i don't have the ability",
]

# A few hundred examples use a literal placeholder ("no input", "<no input>",
# "noinput", ...) instead of actually leaving the input field empty. Left in,
# that text ends up glued onto the instruction as if it were real content.
NO_INPUT = re.compile(r"^[<\[]?\s*no\s*input\s*(required)?\s*[>\].,]*$",
                      re.IGNORECASE)

# Special tokens. Keep these first and in this order -- the C side assumes it.
UNK, USER, BOT, END = "<unk>", "<user>", "<bot>", "<end>"
SPECIALS = [UNK, USER, BOT, END]

WORD = re.compile(r"[a-z']+|[0-9]+|[.,!?;:]")


def download(url: str, name: str, min_size: int) -> None:
    DATA.mkdir(exist_ok=True)
    target = DATA / name
    if target.exists() and target.stat().st_size > min_size:
        return
    print(f"downloading {name} ...", flush=True)
    try:
        with urllib.request.urlopen(url, timeout=300) as response:
            target.write_bytes(response.read())
    except Exception as err:
        sys.exit(f"could not download {name}: {err}\n"
                 f"Put it in {DATA} by hand and run this again.")
    print(f"  {target.stat().st_size // 1024} KB")


def tokenize(text: str) -> list[str]:
    """Lower case words, numbers, and the punctuation that changes tone."""
    return WORD.findall(text.lower())


def is_messy(text: str) -> bool:
    """True when the text is mostly code, a table, or markup -- not prose."""
    body = [c for c in text if not c.isspace()]
    if not body:
        return True
    odd = sum(1 for c in body if not ALLOWED_CHARS.match(c.lower()))
    return (odd / len(body)) > 0.12


def leaks_identity(text: str) -> bool:
    lowered = text.lower()
    return any(phrase in lowered for phrase in IDENTITY_LEAKS)


def load_alpaca() -> list[tuple[list[str], list[str]]]:
    """(prompt, output) pairs, already word-split, worth learning from."""
    raw = json.loads((DATA / ALPACA_FILE).read_text(encoding="utf-8"))
    kept: list[tuple[list[str], list[str]]] = []
    dropped = Counter()

    for item in raw:
        instruction = item.get("instruction", "").strip()
        extra = item.get("input", "").strip()
        if NO_INPUT.match(extra):
            extra = ""
        output = item.get("output", "").strip()
        prompt = f"{instruction} {extra}".strip() if extra else instruction

        if not prompt or not output:
            dropped["empty"] += 1
            continue
        if is_messy(prompt) or is_messy(output):
            dropped["code_or_markup"] += 1
            continue
        if leaks_identity(output):
            dropped["claims_to_be_another_ai"] += 1
            continue

        prompt_words = tokenize(prompt)
        output_words = tokenize(output)

        if len(prompt_words) > MAX_PROMPT_WORDS:
            dropped["prompt_too_long"] += 1
            continue
        if not (MIN_OUTPUT_WORDS <= len(output_words) <= MAX_OUTPUT_WORDS):
            dropped["output_wrong_length"] += 1
            continue

        kept.append((prompt_words, output_words))

    print(f"  alpaca: kept {len(kept):,} of {len(raw):,} examples")
    for reason, count in dropped.most_common():
        print(f"    dropped {count:,} ({reason})")
    return kept


WIKI_TITLE = re.compile(r"^ = ([^=].*[^=]) = *$")

# What to ask for a given article title. Rotates so the model does not learn
# to always answer the exact same way.
WIKI_PROMPTS = [
    "tell me about {}",
    "what is {}",
    "what can you tell me about {}",
    "give me some information about {}",
    "describe {}",
]


def load_wiki() -> list[tuple[list[str], list[str]]]:
    """
    (prompt, output) pairs made from real Wikipedia article openings, framed
    as "tell me about X" -> the article's own summary paragraph.

    To point this at something else instead -- your own notes, a book, a
    different topic dump -- replace WIKI_URL above (or write your own loader
    with this same shape) and keep this function's return type: a list of
    (prompt_words, output_words) tuples, same as load_alpaca().
    """
    raw = (DATA / WIKI_FILE).read_text(encoding="utf-8", errors="replace")
    lines = raw.split("\n")
    kept: list[tuple[list[str], list[str]]] = []
    dropped = Counter()
    seen_titles = 0

    i = 0
    while i < len(lines):
        match = WIKI_TITLE.match(lines[i])
        if match is None:
            i += 1
            continue
        title = match.group(1).strip()
        seen_titles += 1

        j = i + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
        paragraph = lines[j].strip() if j < len(lines) else ""
        i = j + 1

        if "<unk>" in title or ";" in title or len(title.split()) > 12:
            dropped["bad_title"] += 1
            continue
        if not paragraph:
            dropped["bad_paragraph"] += 1
            continue

        # WikiText masks rare words as <unk> -- usually just a handful in an
        # otherwise fine paragraph. A few missing words barely matter to a
        # model this size, so drop the marker rather than the whole thing;
        # only give up on paragraphs where it is too dense to make sense of.
        words = paragraph.split()
        unk_rate = sum(1 for w in words if "<unk>" in w) / len(words)
        if unk_rate > 0.15:
            dropped["too_many_unknown_words"] += 1
            continue
        paragraph = re.sub(r"\s*<unk>\s*", " ", paragraph).strip()

        if not paragraph or is_messy(paragraph):
            dropped["bad_paragraph"] += 1
            continue

        # WikiText's own escaping for punctuation stuck inside a word/number.
        paragraph = (paragraph.replace("@-@", "-").replace("@,@", ",")
                    .replace("@.@", "."))
        title_clean = title.replace("@-@", "-")

        prompt_words = tokenize(WIKI_PROMPTS[seen_titles % len(WIKI_PROMPTS)]
                                .format(title_clean))
        output_words = tokenize(paragraph)

        if len(output_words) < MIN_OUTPUT_WORDS:
            dropped["too_short"] += 1
            continue
        # Encyclopedia leads run long; truncating the summary is fine here --
        # unlike a dialogue turn, there is no earlier context being cut off,
        # so "the answer can stop here" is simply true of a shorter summary.
        output_words = output_words[:MAX_OUTPUT_WORDS]

        kept.append((prompt_words, output_words))

    print(f"  wikitext: kept {len(kept):,} of {seen_titles:,} articles")
    for reason, count in dropped.most_common():
        print(f"    dropped {count:,} ({reason})")
    return kept


def main() -> int:
    download(ALPACA_URL, ALPACA_FILE, min_size=1_000_000)
    download(WIKI_URL, WIKI_FILE, min_size=1_000_000)

    print("reading the datasets ...", flush=True)
    examples = load_alpaca() + load_wiki()
    print(f"  {len(examples):,} examples total")

    vocab_path = DATA / "vocab.txt"
    counts = Counter(word for prompt, output in examples
                     for word in prompt + output)

    if vocab_path.exists():
        # A trained model's token embeddings are tied to word -> id, so once
        # a vocabulary has been used for real training it stays fixed: adding
        # a new data source must never renumber it out from under an existing
        # checkpoint. New words this source brings just fall back to <unk>,
        # the same as any other word the model has not seen before.
        vocab = vocab_path.read_text(encoding="utf-8").splitlines()
        print(f"  reusing the existing {len(vocab):,}-word vocabulary "
              f"(delete data/vocab.txt to rebuild it from scratch)")
    else:
        common = [w for w, _ in counts.most_common(VOCAB_SIZE - len(SPECIALS))]
        vocab = SPECIALS + common
        print(f"  building a new {len(vocab):,}-word vocabulary")

    index = {word: number for number, word in enumerate(vocab)}
    covered = sum(counts.get(w, 0) for w in vocab) / max(1, sum(counts.values()))
    print(f"  covers {covered:.1%} of this text")

    print("writing the training stream ...", flush=True)
    stream: list[int] = []
    readable: list[str] = []
    skipped = 0

    for prompt_words, output_words in examples:
        prompt_ids = [index.get(w, 0) for w in prompt_words]
        output_ids = [index.get(w, 0) for w in output_words]
        unk_rate = (prompt_ids.count(0) + output_ids.count(0)) / \
                   (len(prompt_ids) + len(output_ids))
        if unk_rate > MAX_UNK_RATE:
            skipped += 1
            continue

        stream.append(index[USER])
        stream.extend(prompt_ids)
        stream.append(index[BOT])
        stream.extend(output_ids)
        stream.append(index[END])

        readable.append(f"{USER} {' '.join(prompt_words)}")
        readable.append(f"{BOT} {' '.join(output_words)}")
        readable.append(END)

    (DATA / "vocab.txt").write_text("\n".join(vocab) + "\n", encoding="utf-8")
    (DATA / "corpus.bin").write_bytes(struct.pack(f"<{len(stream)}H", *stream))
    (DATA / "corpus.txt").write_text("\n".join(readable) + "\n", encoding="utf-8")

    print(f"  {len(stream):,} tokens written to data/corpus.bin")
    print(f"  {skipped:,} examples skipped as too unfamiliar")
    print()
    print("Now train on it:  python3 run.py --train 30")
    return 0


if __name__ == "__main__":
    sys.exit(main())
