#!/usr/bin/env python3
"""
prepare.py -- turn instruction data into something the model can learn from.

It takes the Stanford Alpaca dataset (52,000 instruction -> response pairs,
written to train a helpful assistant rather than transcribed from film scripts),
cleans it up, builds a vocabulary, and writes the whole thing out as a stream of
token numbers for engine/train_lm.c to train on.

    python3 train/prepare.py            # downloads the dataset if it is missing

Everything lands in data/:

    alpaca_data.json   raw dataset (downloaded once)
    vocab.txt           one word per line, most common first
    corpus.bin           the training data: little endian uint16 token ids
    corpus.txt           the same thing readable, for when you are curious
"""

from __future__ import annotations

import json
import re
import struct
import sys
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

SOURCE_URL = ("https://raw.githubusercontent.com/tatsu-lab/"
              "stanford_alpaca/main/alpaca_data.json")
RAW_FILE = "alpaca_data.json"

VOCAB_SIZE = 8000          # words kept; everything else becomes <unk>
MAX_PROMPT_WORDS = 50      # instruction (+ input), combined
MAX_OUTPUT_WORDS = 80      # drop the long-tail essays; keeps windows short
MIN_OUTPUT_WORDS = 1
MAX_UNK_RATE = 0.15        # skip an example that is mostly words we do not know

# Anything outside these characters (case-insensitive) is a sign the answer is
# code, a table, or markdown -- not the kind of prose a word-level model can
# represent -- so a high ratio of them means "skip this one".
ALLOWED_CHARS = re.compile(r"[a-z0-9.,!?;:' \n\-]")

# Alpaca's answers were generated by an OpenAI model, and it shows: some of them
# claim to *be* one. Vespra is trained from scratch, on your machine, by nobody's
# API -- so training examples that assert otherwise are dropped rather than
# taught as if they were true.
IDENTITY_LEAKS = [
    "language model", "openai", "chatgpt", "gpt-3", "gpt-4", "gpt3", "gpt4",
    "gpt model", "gpt language", "as a gpt", "nooutput", "cannot be fulfilled",
    "as an ai", "i am an ai", "i'm an ai", "an ai assistant",
    "artificial intelligence created by", "trained by openai",
    "i do not have the ability", "i don't have the ability",
]

# A few hundred examples use a literal placeholder ("no input", "<no input>",
# "noinput", ...) instead of actually leaving the input field empty. Left in,
# that text ends up glued onto the instruction as if it were real content.
NO_INPUT = re.compile(r"^[<\[]?\s*no\s*input\s*(required)?\s*[>\].,]*$",
                      re.IGNORECASE)

# Special tokens. Keep these first and in this order -- the C side assumes it.
UNK, USER, BOT, END = "<unk>", "<user>", "<bot>", "<end>"
SPECIALS = [UNK, USER, BOT, END]

WORD = re.compile(r"[a-z']+|[0-9]+|[.,!?;:]")


def download() -> None:
    DATA.mkdir(exist_ok=True)
    target = DATA / RAW_FILE
    if target.exists() and target.stat().st_size > 1_000_000:
        return
    print(f"downloading {RAW_FILE} ...", flush=True)
    try:
        with urllib.request.urlopen(SOURCE_URL, timeout=300) as response:
            target.write_bytes(response.read())
    except Exception as err:
        sys.exit(f"could not download {RAW_FILE}: {err}\n"
                 f"Put it in {DATA} by hand and run this again.")
    print(f"  {target.stat().st_size // 1024} KB")


def tokenize(text: str) -> list[str]:
    """Lower case words, numbers, and the punctuation that changes tone."""
    return WORD.findall(text.lower())


def is_messy(text: str) -> bool:
    """True when the text is mostly code, a table, or markup -- not prose."""
    body = [c for c in text if not c.isspace()]
    if not body:
        return True
    odd = sum(1 for c in body if not ALLOWED_CHARS.match(c.lower()))
    return (odd / len(body)) > 0.12


def leaks_identity(text: str) -> bool:
    lowered = text.lower()
    return any(phrase in lowered for phrase in IDENTITY_LEAKS)


def load_examples() -> list[tuple[str, str]]:
    """(prompt, output) pairs, already word-split, worth learning from."""
    raw = json.loads((DATA / RAW_FILE).read_text(encoding="utf-8"))
    kept: list[tuple[list[str], list[str]]] = []
    dropped = Counter()

    for item in raw:
        instruction = item.get("instruction", "").strip()
        extra = item.get("input", "").strip()
        if NO_INPUT.match(extra):
            extra = ""
        output = item.get("output", "").strip()
        prompt = f"{instruction} {extra}".strip() if extra else instruction

        if not prompt or not output:
            dropped["empty"] += 1
            continue
        if is_messy(prompt) or is_messy(output):
            dropped["code_or_markup"] += 1
            continue
        if leaks_identity(output):
            dropped["claims_to_be_another_ai"] += 1
            continue

        prompt_words = tokenize(prompt)
        output_words = tokenize(output)

        if len(prompt_words) > MAX_PROMPT_WORDS:
            dropped["prompt_too_long"] += 1
            continue
        if not (MIN_OUTPUT_WORDS <= len(output_words) <= MAX_OUTPUT_WORDS):
            dropped["output_wrong_length"] += 1
            continue

        kept.append((prompt_words, output_words))

    print(f"  kept {len(kept):,} of {len(raw):,} examples")
    for reason, count in dropped.most_common():
        print(f"    dropped {count:,} ({reason})")
    return kept


def main() -> int:
    download()

    print("reading the dataset ...", flush=True)
    examples = load_examples()

    print("building the vocabulary ...", flush=True)
    counts = Counter(word for prompt, output in examples
                     for word in prompt + output)
    common = [word for word, _ in counts.most_common(VOCAB_SIZE - len(SPECIALS))]
    vocab = SPECIALS + common
    index = {word: number for number, word in enumerate(vocab)}
    covered = sum(counts[w] for w in common) / max(1, sum(counts.values()))
    print(f"  {len(vocab):,} words, covering {covered:.1%} of the text")

    print("writing the training stream ...", flush=True)
    stream: list[int] = []
    readable: list[str] = []
    skipped = 0

    for prompt_words, output_words in examples:
        prompt_ids = [index.get(w, 0) for w in prompt_words]
        output_ids = [index.get(w, 0) for w in output_words]
        unk_rate = (prompt_ids.count(0) + output_ids.count(0)) / \
                   (len(prompt_ids) + len(output_ids))
        if unk_rate > MAX_UNK_RATE:
            skipped += 1
            continue

        stream.append(index[USER])
        stream.extend(prompt_ids)
        stream.append(index[BOT])
        stream.extend(output_ids)
        stream.append(index[END])

        readable.append(f"{USER} {' '.join(prompt_words)}")
        readable.append(f"{BOT} {' '.join(output_words)}")
        readable.append(END)

    (DATA / "vocab.txt").write_text("\n".join(vocab) + "\n", encoding="utf-8")
    (DATA / "corpus.bin").write_bytes(struct.pack(f"<{len(stream)}H", *stream))
    (DATA / "corpus.txt").write_text("\n".join(readable) + "\n", encoding="utf-8")

    print(f"  {len(stream):,} tokens written to data/corpus.bin")
    print(f"  {skipped:,} examples skipped as too unfamiliar")
    print()
    print("Now train on it:  python3 run.py --train 30")
    return 0


if __name__ == "__main__":
    sys.exit(main())
